name: CI
on:
  push:
    branches:
      - fluid
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 查询分支
        uses: actions/checkout@v2

      - name: Setup Node.js 10.x 
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
    
      - name: Setup Hexo Dependencies
        run: |
          npm install hexo-cli -g
          npm install

      - name: 清除Hexo
        uses: heowc/action-hexo@main
        with:
          args: clean

      - name: 生成Hexo
        uses: heowc/action-hexo@main
        with:
          args: generate

      - name: 部署到master分支
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HEXO_CITOKEN }}
          external_repository: novpath/novpath.github.io
          publish_branch: master
          publish_dir: ./public